### ISSUE TITLE
[bug] diff failed in react-diff-view@2.4.4

### ISSUE THREAD

**Issue by dancerphil** [otakustay/react-diff-view#104]
This is a bug in react-diff-view@2.4.4

## reproduce

goto https://otakustay.github.io/react-diff-view/ and choose `beauty a diff`

```diff
diff --git a/sys_test/diff/diff_parallel.yaml b/sys_test/diff/diff_parallel.yaml
old mode 100644
new mode 100755
```

will fail.

Which is success in react-diff-view@2.4.1

**Comment by otakustay** [comment]
not stale

**Comment by Waize** [comment]
Got the same issue here

**Comment by otakustay** [comment]
Hi @dancerphil this is a feature in demo site processing diff text, it by default appends a git diff header (`diff --git a/xxx b/xxx`) to diff text, however given text already includes one.

Is this just an issue with the demo site, or it could actually crash using `<Diff />` component? what is the actual input of `parseDiff` function from `react-diff-view`?

**Comment by dancerphil** [comment]
> Is this just an issue with the demo site, or it could actually crash using `<Diff />` component?

It is a real issue. The diff above is the actual input.

I'm locking at 2.4.1 to avoid being affected.

**Comment by otakustay** [comment]
`2.4.5` should fix this
