### ISSUE TITLE
Not able to parse some diffText

### ISSUE THREAD

**Issue by lomse** [otakustay/react-diff-view#107]
Hi All,
Thanks for this amazing library. 
I'm having hard time understanding why it is not able to parse the strings below:

```
@@ -7,6 +7,9 @@ stages:
 #  - scan
   - deploy
 
+include:
+  - template: depl/config.yml
+
 unit tests:
   image: maven:3-jdk-8
   stage: test
```

```
@@ -7,6 +7,9 @@ stages:
 #  - scan
   - deploy
 
+include:
+  - template: depl/config-2.yml
+
 unit tests:
   image: maven:3-jdk-8
   stage: test
```

I keep getting the error as shown on the screenshot below:

![Screenshot 2020-12-03 at 4 27 11 PM](https://user-images.githubusercontent.com/4754182/101057852-6916f700-3584-11eb-9c4a-1e8c6e319929.png)

What am I missing please? Below is my implementation

```
type ChangesProps = {
  diffs: DiffType[]
}

export const Changes: React.FC<ChangesProps> = ({ diffs }) => {

  return (
    <React.Fragment>
      {diffs.map((diffObj, index) => {
        const diffText = diffObj.diff;
        console.log(diffText)
        const files = parseDiff(diffText) // Error thrown here.

        console.log({files})

        const renderFile = ({ oldRevision, newRevision, type, hunks }) => (
          <Diff key={oldRevision + '-' + newRevision} viewType="unified" diffType={type} hunks={hunks}>
            {hunks => hunks.map(hunk => <Hunk key={hunk.content} hunk={hunk} />)}
          </Diff>
        )

        return (
          <div key={index}>
            {files.map(renderFile)}
          </div>
        )
      })}
    </React.Fragment>
  )
}
```

**Comment by lomse** [comment]
Any idea on this issue?

**Comment by otakustay** [comment]
This should definitely be a bug in our parser, I'll take a look at it tomorrow

**Comment by otakustay** [comment]
I did a little dig into this issue, this library currently support 2 format of diff.

Git diff:

```
diff --git a/test/fixture/test/ci.go b/test/fixture/test/ci.go
index 6829b8a2..4c565f1b 100644
--- a/test/fixture/test/ci.go
+++ b/test/fixture/test/ci.go
[content]
```

Or unidiff:

```
--- /test/fixture/test/ci.go 2002-02-21 23:30:39.942229878 -0800
+++ /test/fixture/test/ci.go 2002-02-21 23:30:50.442260588 -0800
[content]
```

Note both of them have some lines of **header** containing metadata like changed filename, when git diff is not detected, this library assume it as a unidiff and try to parse filenames from header lines, then normalize it to a git diff for further parse.

In your case, the diff text doesn't contain either git diff header nor unidiff header, we cannot detect a filename from it, this causes a malform of normalized diff structure, which raises an error.

I'd receomment you to add a git diff header manually to your diff text, the filename inside it can be mocked to any path like:

```js
const CONTANT_GIT_DIFF_HEADER = `diff --git a/config.yml b/config.yml
index 1111111..2222222 100644
--- a/config.yml
+++ b/config.yml`;

const diffText = CONTENT_GIT_DIFF_HEADER + '\n' + rawDiffText;
```
