### ISSUE TITLE
Tokenize resources

### ISSUE THREAD

**Issue by asim-shrestha** [otakustay/react-diff-view#116]
I'm trying to add syntax highlighting to my diffs but can't find any resources on how to do this. Ive added this tokenize function and have passed the tokens to my <Diff/>

```
export const Tokenize = (hunks: any, fileExtension: string) => {
    if (!hunks) {
        return undefined;
    }

    const options = {
        highlight: true,
        refractor: refractor,
        oldSource: '',
        language: 'jsx',
        enhancers: [],
    };

    try {
        return tokenize(hunks, options);
    } catch (ex) {
        return undefined;
    }
};
```

**Comment by otakustay** [comment]
I've created a demo sandbox: https://codesandbox.io/s/react-diff-view-syntax-highlight-116yv?file=/src/App.js

The key is the `tokenize` function call, welcome any further questions

**Comment by asim-shrestha** [comment]
thanks! i didn't realize we needed CSS imports for the highlighting
