### ISSUE TITLE
Diff View component causes crash in Safari

### ISSUE THREAD

**Issue by rbreeze** [otakustay/react-diff-view#129]
After upgrading `react-diff-view` from `v2.1.4` to `v2.4.7`, our application crashes in Safari ` v14.1.1` with error:

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

This is due to a bug in `normalize-url`: https://github.com/sindresorhus/normalize-url/issues/105

**Comment by otakustay** [comment]
How do you use `react-diff-view`? I tried to figure out why `normalize-url` is introduced:

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "normalize-url"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "normalize-url@3.3.0"
info Reasons this module exists
   - "cssnano#cssnano-preset-default#postcss-normalize-url" depends on it
   - Hoisted from "cssnano#cssnano-preset-default#postcss-normalize-url#normalize-url"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "20KB"
info Disk size with transitive dependencies: "20KB"
info Number of shared dependencies: 0
✨  Done in 0.34s.
```

Seems this is only a dev dependency and will not go into the npm bundle. I also tried to search "normalize" and "url" from `es/index.js` and didn't find any `normalize-url` related code

For `react-diff-view` itself, it doen't specify any dependencies, all deps are dev deps and should be installed when you introduce this library
