### ISSUE TITLE
Double margin when using anchor in gutter?

### ISSUE THREAD

**Issue by oBusk** [otakustay/react-diff-view#131]
I've enabled `gutterType="anchor"` recently and noticed that I was getting linebreaks when line numbers are 3 digits. Looks like the styling sets the padding on both the cell and the anchor? 

https://github.com/otakustay/react-diff-view/blob/v2.4.7/src/styles/index.css#L47

![image](https://user-images.githubusercontent.com/13413409/127579074-95e5d6fa-4e7a-4855-b968-28b8d3be9f0f.png)

**Comment by otakustay** [comment]
Published `v2.4.8` including this issue
