### ISSUE TITLE
Support  typescript

### ISSUE THREAD

**Issue by tientkc** [otakustay/react-diff-view#135]
I'm using Libs in my project but I got a issue when I convert this project to using typescrpit: 
`
TypeError: children is not a function
Diff/index.js:94
   91 | 
   92 | return (
   93 |     <Provider value={{...remainings, monotonous}}>
> 94 |         <table
   95 | ^               ref={root}
   96 |             className={classNames('diff', `diff-${viewType}`, className)}
   97 |             onMouseDown={onTableMouseDown}
`
So you can update for project using typescript?

**Comment by otakustay** [comment]
not stale, working on it

**Comment by otakustay** [comment]
We introduced TypeScript in version 4, please see https://github.com/otakustay/react-diff-view/discussions/190
