### ISSUE TITLE
readme for widget demo/example not found

### ISSUE THREAD

**Issue by daleperforce** [otakustay/react-diff-view#136]
Reading the readme.md for widget it says

> For a more complex case, you can reference the example in demo/File.js about implementing code comments with the widgets prop.

But when you click the demo/File.js it goes to a page not found. Is this example somewhere for us to see and read?

**Comment by otakustay** [comment]
Sorry, it is current here: https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/index.js#L55-L79

The demo doesn't implement the full comment functionality, it stops on showing a "add comment" button on each line
