### ISSUE TITLE
How to highlight the character in split mode

### ISSUE THREAD

**Issue by ywu151** [otakustay/react-diff-view#138]
The screenshot in Readme highlights the different characters with a darker color. While my component doesn't highlight the different characters.
My UI
<img width="508" alt="Screen Shot 2021-08-13 at 4 56 21 PM" src="https://user-images.githubusercontent.com/33992458/129427972-1c60944c-12b4-47bb-925f-28296e7e4fae.png">
UI in Readme
<img width="701" alt="Screen Shot 2021-08-13 at 4 56 25 PM" src="https://user-images.githubusercontent.com/33992458/129427978-3ffc651c-2098-4f1f-b66f-8030d442a1c2.png">

**Comment by otakustay** [comment]
This feature is named "mark edits", here is a sandbox demo: https://codesandbox.io/s/react-diff-view-mark-edits-demo-8ndcl?file=/src/index.js
