### ISSUE TITLE
Option to hide line numbers

### ISSUE THREAD

**Issue by joelburget** [otakustay/react-diff-view#14]
It would be great if this tool had an option to hide line numbers. I hacked it with these rules but this seems brittle.

```
.diff-gutter {
  visibility: collapse;
}
table.diff {
  margin-left: -14ch;
}
```

**Comment by otakustay** [comment]
Try 1.5.0, pass `hideGutter` prop to `Diff` component:

```js
<Diff hideGutter ...otherProps />
```

**Comment by joelburget** [comment]
Perfect -- thank you :)
