### ISSUE TITLE
How to add language highlight?

### ISSUE THREAD

**Issue by justanotheranonymoususer** [otakustay/react-diff-view#142]
I tried to use [the sandbox](https://codesandbox.io/s/react-diff-view-mark-edits-demo-8ndcl) and change the tokenizer options as said in the readme:

```js
    const options = {
        highlight: true,
        language: 'cpp',
        refractor: refractor,
        enhancers: [markEdits(hunks, {type: 'block'})],
    };
```

You can see the result here: https://codesandbox.io/s/react-diff-view-mark-edits-demo-forked-7y5ni?file=/src/tokenize.js

But there's no highlighting, and also the block diff marks are gone:
![image](https://user-images.githubusercontent.com/5781692/135735192-62d254ae-0fd6-4021-a71e-b5b049e49412.png)

What am I doing wrong?

**Comment by otakustay** [comment]
There are several reasons: 

1. `react-diff-view` seems to support only `refractor 3.x`, current `4.x` version is not compatible
2. We need a syntax css, here I suggest [prism-themes](https://www.npmjs.com/package/prism-themes), add `import 'prism-themes/themes/prism-vs.css';` to `index.js`

This is a fixed sandbox: https://codesandbox.io/s/react-diff-view-mark-edits-demo-forked-wc1w1?file=/src/index.js

**Comment by justanotheranonymoususer** [comment]
Thanks, perhaps it's best to update the readme.
