### ISSUE TITLE
Support dark scheme out of the box

### ISSUE THREAD

**Issue by justanotheranonymoususer** [otakustay/react-diff-view#144]
Transfer the dark scheme colors from here:
https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/diff.global.less
to here:
https://github.com/otakustay/react-diff-view/blob/master/src/styles/index.css

And why are there many other differences?

**Comment by otakustay** [comment]
`site` is actually a user-land demonstration, from the initial release of `react-diff-view`, we received a bunch of user-land use cases like commenting, variable themes, dark mode, etc...

Most of the feature requests can be implemented on top of current `react-diff-view` and we're not going to build too many minor functions into the core with the result of a large size.

For the dark scheme issue, it requires css variable based styles and an entire different css, this is a BREAKING CHANGE, so we're not adding it to current major version. A variable based style solution will be in the next major, which may not appear in near future

**Comment by justanotheranonymoususer** [comment]
I understand, thanks.
