### ISSUE TITLE
Information about "No newline at end of file" does not come through

### ISSUE THREAD

**Issue by davissorenson** [otakustay/react-diff-view#15]
With the following diff:

    diff --git a/test1.csv b/test2.csv
    index 5aa24aea..73b5d44a 100644
    --- a/test1.csv
    +++ b/test2.csv
    @@ -1,3 +1,3 @@
     abc;def
     123;456
    -789;101
    \ No newline at end of file
    +789;101

Using `parseDiff` on this, the "No newline at end of file" information is thrown away. It would be really nice if this information was added.

**Comment by otakustay** [comment]
It's possible to add this information to `parseDiff`'s output, such as `oldEndingNewLine` and `newEndingNewLine` boolean properties in each file, however we may not provide a visual look in `Diff` component

**Comment by davissorenson** [comment]
That would be enough information for our use case. 👍

**Comment by otakustay** [comment]
`1.7.0` may fix this issue, we have `oldEndingNewLine` and `newEndingNewLine` properties on each file, their values are `true` by default, when `\ No newline at end of file` is reached, the value changes to `false`
