### ISSUE TITLE
[Question] Black theme ?

### ISSUE THREAD

**Issue by NicoAdrian** [otakustay/react-diff-view#150]
Is there any black theme available ?

**Comment by otakustay** [comment]
Our demo site implements a dark theme, 2 steps:

1. Override diff component's style with css variable and provide a dark theme: https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/diff.global.less#L20-L38
2. Override `refactor`'s syntax with variables and a dark theme: https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/syntax.global.less
