### ISSUE TITLE
Is it possible to add some styling to certain lines inside the hunk based on some condition.

### ISSUE THREAD

**Issue by lastlap** [otakustay/react-diff-view#152]
I wanted to add some styling, like a background color to some lines which have certain fixed words defined by me. Is it possible to add a custom class to these lines only? I'm able to get the lines from the hunk based on my condition by using the "MyDiff" logic given in documentation. Can I add some styling to it as well?

**Comment by otakustay** [comment]
Unfortunately not in current version, but we may support it by adding some props, however it is not actually possible to "make a row with custom class name" sine in split vie a row (`<tr>`) can be a combination of 2 changes (a insertion and a deletion), in the data model we can only support cusmize class names over gutter (`<td> with line number) and code (`<td>` with actual code), so all class names are placed on `<td>` elements
