### ISSUE TITLE
Dependencies moved to devDependencies

### ISSUE THREAD

**Issue by patlillis** [otakustay/react-diff-view#153]
Release v2.4.5 broke our site because all of the `dependencies` in package.json got moved into `devDependencies`. Looks like this commit is the culprit: https://github.com/otakustay/react-diff-view/commit/fa7521328bef7a8e2c0c21df7d81f14dfcdc1b0f

**Comment by otakustay** [comment]
I reverted this dependency change in `v2.4.9`

This is a bug fix with breaking semantics, `react-diff-view` is bundled at build time, the only `import` statement in its dist is `react` and `prop-types`, we don't expect other dependencies to be imported by this library

You may unexpectedly importing some of `react-diff-view`'s dependencies like `diff-match-patch`, if this is the case I recommend installing them directly

I'll keep these dependencies in later 2.x versions but remove then in the next major release
