### ISSUE TITLE
Failed prop type: Invalid prop `diffType` of value `new` supplied to `Diff`

### ISSUE THREAD

**Issue by ambrous** [otakustay/react-diff-view#16]
Hi!

Thanks a lot for your lib, it is very useful.

However, I get an error
**Failed prop type: Invalid prop `diffType` of value `new` supplied to `Diff`, expected one of ["add","delete","modify","rename","copy"]**. with a diff like this:

diff --git a/top-1m.csv.zip b/top-1m.csv.zip
new file mode 100644
index 0000000..bffa2e1
Binary files /dev/null and b/top-1m.csv.zip differ

Is there a way to solve it?

I see here is a version of 2.*, however, I use version 1.7.0 (I have installed by `npm install --save react-diff-view`)

Thanks in advance!

**Comment by otakustay** [comment]
Yes, it should be `add`, `delete` or `modify`, `rename` and `copy` are not supported currently, I'll have a look at it, expect to publish new patch version tomorrow
