### ISSUE TITLE
能不能支持编辑，就想webstorm的git版本编辑一样，点击左移右移编辑代码

### ISSUE THREAD

**Issue by ICZhuang** [otakustay/react-diff-view#162]
[demo_image](https://raw.githubusercontent.com/ICZhuang/images/master/Snipaste_2022-02-14_17-34-28.jpg)

**Comment by otakustay** [comment]
我们没有开发编辑功能的计划，建议你可以尝试下`monaco-editor`有没有diff编辑的能力（大概率也没有）
