### ISSUE TITLE
Empty Hunks

### ISSUE THREAD

**Issue by MeteorTony** [otakustay/react-diff-view#168]
I am getting **empty hunks** after using parseDiff(), have no idea what's the problem...
Here is my code:
![githubQ2](https://user-images.githubusercontent.com/61377153/164960181-3adf7ddc-1e44-4c91-a984-062cd8085c16.PNG)

Here is the output:
![githubQ](https://user-images.githubusercontent.com/61377153/164960248-4552c9e3-edc2-4098-9710-27a51249310d.PNG)

No error or warning messages.

**Comment by otakustay** [comment]
Please paste this diff text content here so I can debug

**Comment by MeteorTony** [comment]
```
    const string = `diff --git a/package.json b/package.json
    index ac3c47a..917b855 100644
    --- a/package.json
    +++ b/package.json
    @@ -19,2 +19,3 @@
         "react": "17.0.2",
    +    "react-diff-view": "^2.4.10",
         "react-dom": "17.0.2",`
    console.log(string)

    const files = parseDiff(string);

    console.log(files)
```
Thanks.

**Comment by MeteorTony** [comment]
Oh it seems that I figured out the problem: the template string was having improper indentations (\t)
