### ISSUE TITLE
Site app example functionality issue

### ISSUE THREAD

**Issue by zetekla** [otakustay/react-diff-view#18]
The function for `I want to beautify a diff` seems not working.

Steps to reproduce:
1. Click on the link.
2. Drop the content in the DIFF TEXT area.
3. Click button to 'READ the DIFF'. My assumption here is that button is also used to beautify the text, as seen in `https://codebeautify.org/jsonviewer`. I'm not sure how to get this function to work but see errors and have issue not able to render the presumably 'beautified' beautiful text.

Errors read:
1/ Uncaught TypeError: Cannot read property 'changes' of undefined
2/ react-dom.development.js:14227 The above error occurred in the <App> component:
    in App (created by Region(Configuration))
    in Region(Configuration) (created by establish(Region(Configuration)))
    in establish(Region(Configuration))
3/ index.js:201 Uncaught TypeError: Cannot read property 'changes' of undefined

**Comment by otakustay** [comment]
Can you provide the text you pasted into the textbox?

**Comment by Oscar19921030** [comment]
> The function for `I want to beautify a diff` seems not working.
> 
> Steps to reproduce:
> 
> 1. Click on the link.
> 2. Drop the content in the DIFF TEXT area.
> 3. Click button to 'READ the DIFF'. My assumption here is that button is also used to beautify the text, as seen in `https://codebeautify.org/jsonviewer`. I'm not sure how to get this function to work but see errors and have issue not able to render the presumably 'beautified' beautiful text.
> 
> Errors read:
> 1/ Uncaught TypeError: Cannot read property 'changes' of undefined
> 2/ react-dom.development.js:14227 The above error occurred in the component:
> in App (created by Region(Configuration))
> in Region(Configuration) (created by establish(Region(Configuration)))
> in establish(Region(Configuration))
> 3/ index.js:201 Uncaught TypeError: Cannot read property 'changes' of undefined


> Can you provide the text you pasted into the textbox?

I have this problem too

**Comment by otakustay** [comment]
“Beautify a diff” is a function to format a git diff output into the diff component, can you simply provide me the text you pasted into textbox, so I can reproduce the issue and find a solution

**Comment by NathanBWaters** [comment]
Here's an example of a git diff unified output that I pasted into the box expecting it to work, but nothing happens.  I

```diff --git a/bug_buddy/commands.py b/bug_buddy/commands.py
index 29276f9..4c17724 100644
--- a/bug_buddy/commands.py
+++ b/bug_buddy/commands.py
@@ -26,6 +26,8 @@ from bug_buddy.watcher import watch
 def train_command(src_path: str):
     '''
     Trains a neural network on the available data
+
+    Here is me making a fake diff
     '''
     with session_manager() as session:
         repository = _get_repository_from_src_path(session, src_path)```

<img width="973" alt="image" src="https://user-images.githubusercontent.com/4016602/60118977-6ab37d00-974b-11e9-934c-c50b5cdf94c3.png">

**Comment by NathanBWaters** [comment]
Btw, loving the library so far!

**Comment by otakustay** [comment]
Our site app is currently designed to visualize a more universal unidiff format instead of a git diff, just remove the heading 2 lines (`diff --git` and `index`) to make it work

To be more specific, the site app will automatically prepend these 2 lines from any input, in your case this results a duplicated head lines and fails at diff parsing

<img width="1170" alt="Jietu20190626-103044@2x" src="https://user-images.githubusercontent.com/639549/60146782-75c6e580-97fd-11e9-9629-22c4e7ce5083.png">

**Comment by NathanBWaters** [comment]
thanks @otakustay for the tip!
