### ISSUE TITLE
[Bug] diff being parsed differently on versions >= 2.4.2

### ISSUE THREAD

**Issue by lucasbento** [otakustay/react-diff-view#192]
Hello 👋 

I work on the [React Native Upgrade Helper](https://github.com/react-native-community/upgrade-helper) and upgrading `react-diff-view` from version `2.4.2` to anything above returns a different output when calling `parseDiff` on [this diff](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.69.8..0.71.3.diff).

The breaking difference is that the file `android/gradle/wrapper/gradle-wrapper.jar` has a _hunk_ of `newPath: undefined`, this behaviour started happening in `2.4.3`.

Here's a zip file with the output of both: [version-outputs.zip](https://github.com/otakustay/react-diff-view/files/10862635/version-outputs.zip).

**Comment by otakustay** [comment]
I can reproduce it, going to debug

**Comment by lucasbento** [comment]
thank yoy, @otakustay!

**Comment by otakustay** [comment]
I found a bug handling binary delta diff in our parser and fixed it, this fix ships with `3.0.3` which is in a major version 3.x, will you strongly need it to be backported to 2.x or just advance to 3.x which has [very little breaking changes](https://github.com/otakustay/react-diff-view/discussions/190)?
