### ISSUE TITLE
withTokenizeWorker and Diff

### ISSUE THREAD

**Issue by ornic** [otakustay/react-diff-view#193]
New typescript version breaks connection between `withTokenizeWorker` and `Diff`, both exported from `react-diff-view`.

![image](https://user-images.githubusercontent.com/3350070/222216246-0939165e-32ca-4987-9264-e96650ef81b0.png)

Is this a planned break? If so, are there some simple update to old code? The one in https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/index.tsx have rather different structure.

**Comment by otakustay** [comment]
Please provide me the errored code, I'll try to reproduce and fix it, it should be fully compatible

**Comment by Kondorok** [comment]
https://codesandbox.io/s/gracious-spence-x2yec5?file=/src/App.tsx type error

**Comment by otakustay** [comment]
Please help verify if `3.0.3` fixes this issue

**Comment by ornic** [comment]
Thank you!

https://codesandbox.io/s/dry-sun-5clunm?file=/src/App.tsx

Сodesandbox is having problem loading newest version this fast

![image](https://user-images.githubusercontent.com/3350070/224956999-11247f0d-d408-42ea-b4da-2021f16cb09c.png)

Hope they will update their caches soon.
