### ISSUE TITLE
Is that possible to fix multiline comment tokenize problem without oldSource?

### ISSUE THREAD

**Issue by ensorrow** [otakustay/react-diff-view#195]
Firstly, the new tokenize system is incredibly impressive and greatly enhances the syntax highlight experience compared to version1.x. However, the system encounters a major issue when dealing with unclosed multiline comments, which is unacceptable to our users. Unfortunately, using the oldSource parameter to address this problem is not a viable solution in certain scenarios. For example, if **the full file content is too large** to be tokenized in a browser, the page will freeze. Additionally, changes in the target branch may result in **base content changes**, preventing me from obtaining the appropriate content for oldSource, as this information is not stored in the database. I have attempted to highlight the hunk separately and concatenate them together, but this method did not yield the desired results. 

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/13199771/225613157-fddad93e-60ab-4777-8280-061a571cee16.png">

Is it possible to rectify the multiline comment tokenize issue without relying on oldSource ? Orz

**Comment by ensorrow** [comment]
Need Help🥹

**Comment by otakustay** [comment]
Previously I tried to solve this but had no luck, and this is also a core reason why tokenization system is designed and published :(

One viable but complicated solution is to :

1. Write a [custom refractor syntax](https://github.com/wooorm/refractor#refractorregistersyntax) to simply return a text node for input code
2. Detect if a hunk (or some lines of code) is inside a multiline comment yourself, and highlight this with custom syntax

I would consider the detection is very complex and hard to implement, but maybe you have some tools already did this?
