### ISSUE TITLE
Package should be published not minimized

### ISSUE THREAD

**Issue by bodinsamuel** [otakustay/react-diff-view#196]
Hey,

I have started using this package, it works great thank you :) 
I just encountered two issues:
- The mapping doesn't work in the browser, not sure why but might be related to the second issue
- The package is compiled which makes it hardly debuggable, and increase our own bundle because it will have duplicated compilation stuff (like iterators, babel, etc...) 

If you want to published it compiled and minimized you can have an other folder with it, but having the source in .js + d.ts would be more than awesome, thanks ☺️

**Comment by otakustay** [comment]
Yes exactly, I prepare to do this in next major, changing publish format is a breaking change currently.

For your case, now I'm going to publish both minified and compiled code in a single package, you can `import {Diff} from 'react-diff-view/compiled'

**Comment by bodinsamuel** [comment]
Amazing news, thanks a lot ☺️
