### ISSUE TITLE
How to expand all lines of code

### ISSUE THREAD

**Issue by CocoaTouch123** [otakustay/react-diff-view#203]
hi @otakustay 
in this page https://otakustay.github.io/react-diff-view/ 
Using file-level comparison, I output ORIGINAL TEXT and CHANGED TEXT, how to expand all lines with one click
Looking forward to your reply

**Comment by CocoaTouch123** [comment]
I directly called the expandRange method to operate, I don't know if it is the right way
`<Button onClick={(e)=>{
                      e.stopPropagation();
                      expandRange(1, newCode?.split('\n')?.length + 1);
                    }}>展开全部</Button>`

**Comment by CocoaTouch123** [comment]
@otakustay  你好，我这边使用expandRange(1, Infinity) 的情况下，全部展开会出现代码行数丢失的问题，只展开了旧文件的行数，旧文件后面新增的行数没有显示出来，这是啥问题呢

**Comment by otakustay** [comment]
有具体的示例吗？你是指比如旧文件是：

```
1
2
3
5
6
```

新文件是：

```
1
2
3
4
5
6
7
8
```

然后展开后，`7`和`8`不见了？
