### ISSUE TITLE
3.0.3版本中无法实现语法高亮

### ISSUE THREAD

**Issue by CocoaTouch123** [otakustay/react-diff-view#204]
@otakustay 你好，我使用了最新的3.0.3版本，按照以下链接中的demo无法实现语法高亮，请帮忙看下，谢谢
https://codesandbox.io/s/react-diff-view-with-code-expansion-forked-zj9q74?file=/src/App.js

**Comment by CocoaTouch123** [comment]
> 我把react升级到16.14.0，react-diff-view升级到3.0.3是可用的。react必须16.14.0以上，因为需要`react/jsx-runtime`

我本地项目使用react的版本是18.2.0，react-diff-view的版本是3.0.3.现在是不能显示语法高亮的
然后我拉取了react-diff-view的最新代码，本地运行site，也是不能展示语法高亮的

**Comment by otakustay** [comment]
你有办法在codesandbox上复现吗，不然挺难排查的……

这是我更新后的sandbox，各种依赖都最新版本了：https://codesandbox.io/s/react-diff-view-with-code-expansion-forked-li3lin?file=/src/ExpandButton.js

我看到你的代码里用的是WebWorker做高亮，可能是你构建工具在Worker处理上有什么问题（比如没有`worker-loader`之类的），如果不是特别大量的代码的话，你可以考虑参考sandbox先改成直接高亮的，见`const tokens = useMemo(...)`这一段

**Comment by CocoaTouch123** [comment]
> const tokens =
多谢大佬的回复
我后来在sandbox上修改了react版本和diff-view的版本也能高亮了
我大概发现问题所在了，之前demo的语言一直是text。运行site后，修改语言类型后，demo就可以语法高亮了
![image](https://github.com/otakustay/react-diff-view/assets/10841183/dad09f5d-8486-4159-9f03-d6689bb0b8cd)
但是我本地项目修改中修改了把语言从原来的text改为jsx或者java也还是不能高亮
因为我需要使用完整的功能，添加评论，展开收起代码等功能，所以我在你site的基础上做了参考，我本地确实没有worker-loader
所以就无法识别以下yin引用，因此我把Tokenize.ts文件代码封装了一个worker类
![image](https://github.com/otakustay/react-diff-view/assets/10841183/b9a3cbf9-4245-43ef-b671-cbd3d73eca13)
<img width="634" alt="image" src="https://github.com/otakustay/react-diff-view/assets/10841183/a71026f9-9fba-4294-9e4b-674c191b27a4">
然后添加评论和展开代码这些功能就正常了。不过高亮已经不行
