### ISSUE TITLE
children 返回类型定义有问题，不支持ReactElement[][]

### ISSUE THREAD

**Issue by guoqirong** [otakustay/react-diff-view#206]
![image](https://github.com/otakustay/react-diff-view/assets/57247313/37a68c26-bcae-4689-b254-fa51d47a984d)
children 返回类型定义有问题，需要支持 ReactElement[][]

**Comment by guoqirong** [comment]
实际需要采用 ReactElement[][]，如果用react的<></>套起来，控制台会报key不存在的错误

**Comment by otakustay** [comment]
理论上可以无限套数组……我修一下好了
