### ISSUE TITLE
修复多行注释未闭合时的语法高亮问题

### ISSUE THREAD

**Issue by ensorrow** [otakustay/react-diff-view#207]
![image](https://github.com/otakustay/react-diff-view/assets/13199771/fc5f0197-19f3-41d2-9930-ab1879862606)

由于组件目前是把 Diff 代码连接起来整段交给 refractor 去做解析的，所以在遇到 Diff 区域多行注释未闭合时，高亮的解析结果会出现错误，这个问题在文档中有提到过：

![image](https://github.com/otakustay/react-diff-view/assets/13199771/876893e3-71c7-4b69-86b1-34f426f46573)

目前仅有的解法是拿到 oldSource，算出完整的文件内容两边分别去做语法高亮，但遇到大文件、小 Diff 时，性能受影响比较大。

<img width="1094" alt="image" src="https://github.com/otakustay/react-diff-view/assets/13199771/4d7d2f31-246f-4457-8137-4c55ea5cb95c">

想了解下现在这样设计的原因是什么，不能把 Hunk 的内容分段丢给 refractor 去解析吗 😄

**Comment by ensorrow** [comment]
感谢回复，把 hunk 分成几段分别做 highlight 感觉效果好像也可以接受（相比于目前多行注释未闭合的情况），为啥没有选择这么做呀（图是 Prism 着色一个代码片段的效果）：
![image](https://github.com/otakustay/react-diff-view/assets/13199771/8d843fff-6d64-423f-8119-1cd7f338cc1a)

**Comment by otakustay** [comment]
从我们通用的角度来说，这么做作用也不大，比如一个多行注释的起始`/**`是在没有变化的行里的，那在hunk中就看不出一部分是注释了。这种半吊子的，能解决特定场景，但对普通用户可能引入更多的疑惑的方案，我还是觉得不适合作为一个普适的默认选择

**Comment by ensorrow** [comment]
> 从我们通用的角度来说，这么做作用也不大，比如一个多行注释的起始`/**`是在没有变化的行里的，那在hunk中就看不出一部分是注释了。这种半吊子的，能解决特定场景，但对普通用户可能引入更多的疑惑的方案，我还是觉得不适合作为一个普适的默认选择

理解，感谢回复

**Comment by CocoaTouch123** [comment]
@ensorrow 
Hello, could you please share how you solved this problem later? I'm encountering the same issue. Thank you
