### ISSUE TITLE
多行注释未闭合时的语法高亮问题

### ISSUE THREAD

**Issue by HQ1363** [otakustay/react-diff-view#209]
衔接issues：#207 https://github.com/otakustay/react-diff-view/issues/207

![image](https://github.com/otakustay/react-diff-view/assets/46860462/6fc86aa4-e479-4269-bb5d-6ffa975c9e2c)

按照文档提示，我将oldSource整个传递进去，得到的语法高亮，仍然在遇到 Diff 区域多行注释未闭合时，高亮的解析结果会出现错误的问题。

**Comment by otakustay** [comment]
具体传进来的内容能提供吗，比如弄个sandbox可以排查下

**Comment by CocoaTouch123** [comment]
> 衔接issues：#207 #207
> 
> ![image](https://private-user-images.githubusercontent.com/46860462/269873492-6fc86aa4-e479-4269-bb5d-6ffa975c9e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDc5MTUsIm5iZiI6MTcyNTM0NzYxNSwicGF0aCI6Ii80Njg2MDQ2Mi8yNjk4NzM0OTItNmZjODZhYTQtZTQ3OS00MjY5LWJiNWQtNmZmYTk3NWM5ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjVkODNiNDFiNDk2MzhiZThhYzNlMWI0OWYwYzdiNzUzN2U2N2IwMWFlYjViYjI2OGM0MDUxYTljYWQ1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV0IBbRveAicuT97-2aUb3M8EXqXktLo1cCnCp4ofpk)
> 
> 按照文档提示，我将oldSource整个传递进去，得到的语法高亮，仍然在遇到 Diff 区域多行注释未闭合时，高亮的解析结果会出现错误的问题。

请教下这个问题后来解决了吗，遇到通样的问题了

**Comment by otakustay** [comment]
提供一个codesandbox的复现吧，我还能进一步看看

**Comment by CocoaTouch123** [comment]
> 提供一个codesandbox的复现吧，我还能进一步看看
@otakustay 链接如下：
https://codesandbox.io/p/sandbox/react-diff-view-with-code-expansion-forked-n9z7l6
辛苦帮忙看下，你点击190行下面的'Expand Down'就能复现
![image](https://github.com/user-attachments/assets/8d08f1d3-2b05-476b-81b6-6a0320488b69)
