### ISSUE TITLE
3版本，codeEvents失效

### ISSUE THREAD

**Issue by Bairuina** [otakustay/react-diff-view#213]
参考demo：
https://codesandbox.io/p/sandbox/react-diff-view-codeevents-5k9ns4?file=%2Fsrc%2Findex.js%3A22%2C23

**Comment by otakustay** [comment]
感谢，文档描述是错了，`codeEvents`和`widgets`属性现在是在`Diff`组件上的，我修改了一下你的代码：https://codesandbox.io/p/sandbox/react-diff-view-codeevents-forked-9ql8f2?file=%2Fsrc%2Findex.js%3A62%2C38

我会后续更新文档，还请先按调整后的代码使用，`Hunk`组件现在只有一个`hunk`属性了
