### ISSUE TITLE
Comment on left side on split view shows on the whole length

### ISSUE THREAD

**Issue by alex-semenyuk** [otakustay/react-diff-view#215]
Comment on left side on split view shows on the whole length - include right side.
Is it possible that it shows only on length left side for which it was left?
@otakustay

**Comment by otakustay** [comment]
I don't quite understand this, could you attach a screenshot to explain it in detail?

**Comment by alex-semenyuk** [comment]
@otakustay Yes, we can see that on README's overview. I don't want that comment, which we left for left side, is continued on right side (crossed on the screen). 
<img width="1169" alt="split-view" src="https://github.com/otakustay/react-diff-view/assets/5480441/d52a7296-5f76-45c6-81aa-8ba245e44d9b">

**Comment by alex-semenyuk** [comment]
@otakustay Thanks for answering. 
Yes, please provide an example when you have time
