### ISSUE TITLE
Are there examples available?

### ISSUE THREAD

**Issue by hhbilly** [otakustay/react-diff-view#22]
I'm new to react and would like to learn more by implementing a site using this amazing component. 

I'm having some trouble getting anything working. Are there examples/demos available on either [codepen](https:codepen.io) or [codesandbox](https://codesandbox.io)?

**Comment by hhbilly** [comment]
Thanks a lot! Very helpful to get something worknig.  As this works for v1.7.0 it would be great to see a similar example working with latest. This issue can probably be closed now.

**Comment by otakustay** [comment]
2.0 will be published soon, will update examples then :)
