### ISSUE TITLE
如何禁用插件的shift按键，而是使用用户自定义的shift键操作

### ISSUE THREAD

**Issue by CocoaTouch123** [otakustay/react-diff-view#224]
@otakustay 帮忙看下如何处理
我现在通过自定义事件获取多行代码，然后进行comment。需要自定义shift按键。如何处理呢

**Comment by otakustay** [comment]
我不是很确定你是怎么用的，默认的核心是没有劫持SHIFT的，只在官网的DEMO里有这个逻辑（`useSelection`），你是否直接拿了这个hook来用呢？

**Comment by CocoaTouch123** [comment]
> 我不是很确定你是怎么用的，默认的核心是没有劫持SHIFT的，只在官网的DEMO里有这个逻辑（`useSelection`），你是否直接拿了这个hook来用呢？

谢谢你的回复，已经解决了。确实用了这个hook
