### ISSUE TITLE
Plan to release 2.x under react >= 16.7.0

### ISSUE THREAD

**Issue by otakustay** [otakustay/react-diff-view#24]
Since react introduces hooks in `16.7.0`, we should finally publish our `2.0.0` under this  version to prevent another major version only for upgrading the react peer dependency restriction.

Currently we have some todos:

1. How many of our hocs can be shipped also in hooks, this can be landed in a minor version in 2.x
2. Are we publishing an `alpha` version to test 2.x before react `16.7.0` is stable

@dancerphil maybe you can have a look at this issue and determine how we could archive the 2.x release

**Comment by dancerphil** [comment]
@otakustay Here is the plan:

1. Publish `2.0.0-alpha.x` and last for a period of time according the `react@16.7` progress
1. Migrate on our  private project and release a `migrate to v2` document
1. Publish 2.0 after stable

**Comment by willdurand** [comment]
Hi @otakustay and @dancerphil, we (AMO team at Mozilla) would like to use your library to build a code review tool for the Firefox add-ons (https://addons.mozilla.org). We're wondering if there are things we could do to help with the `2.x` release.

**Comment by otakustay** [comment]
@willdurand The `2.x` is functionally ready currently, with much less tests than we thought it should have, we have little time in the end of a Chinese year, so test could be late.

The reason we don’t publish an official `2.0.0` release is that we’re waiting for the hooks version of react so we don’t change `peerDependencies` later.

A `2.0.0-alpha.1` version may be published as soon as possible for us to test the `2.x` publicly, @dancerphil do we have any work before we could publish the alpha version?

**Comment by otakustay** [comment]
@willdurand I just published `2.0.0-alpha.1` version with `@next` tag, `npm install react-diff-view@next` will install this version.

This version should be functional, our [demo site](
https://otakustay.github.io/react-diff-view/) uses this version, we will update codesandbox demos to the `2.0.0-alpha.1` version soon.

Glad to hear any updates or issues from you ,we are ready to try our best to collabrate with you on Firefox addon integration.

**Comment by willdurand** [comment]
Thank you, that's good news!

**Comment by otakustay** [comment]
A very comprehensive demo (no syntax highlight, no inline diff): https://codesandbox.io/s/j7lwqj0l63

**Comment by dancerphil** [comment]
Since react@16.8 is released(with hooks), we are going to release react-diff-view@2.0 with peerDependencies of react@16.8

**Comment by otakustay** [comment]
I'd like to publish 2.0 ASAP without any modification to current alpha version, then 2.0.1 will have a refactor to hook based components, 2.1.0 will include hooks along with hocs for enhancements
