### ISSUE TITLE
parseDiff does not process multiple files

### ISSUE THREAD

**Issue by bobsilverberg** [otakustay/react-diff-view#33]
Based on the example at https://github.com/otakustay/react-diff-view/blob/master/README.md#render-diff-hunks, I assumed that `parseDiff` could read a diff with multiple files, and it would return an array with multiple items, one per file. The code of `parseDiff` seems to suggest that as well, but when I pass a diff with multiple files to `parseDiff` it only seems to read the first file and always outputs an array with a single element.

I tried using it with the diff provided as an example at https://github.com/otakustay/react-diff-view/blob/v2.0.0-alpha.1/src/__test__/cases.js#L16, and I saw the same result. The array returned by `parseDiff` only contains one element and it is the first file in the diff.

Is this the expected behaviour, or is this a bug?

**Comment by otakustay** [comment]
I tried the latest version `1.8.1` and get a correct result:

```shell
~/Develop/test » cat test                                                                                                                   otakustay@Reinforce
cat: test: No such file or directory
------------------------------------------------------------
~/Develop/test » cat test.js                                                                                                                otakustay@Reinforce
const diff = `diff --git a/src/index1.js b/src/index1.js
index e69de29..d00491f 100644
--- a/src/index1.js
+++ b/src/index1.js
@@ -0,0 +1 @@
+1
diff --git a/src/index.js b/src/index2.js
index d00491f..0cfbf08 100644
--- a/src/index2.js
+++ b/src/index2.js
@@ -1 +1 @@
-1
+2
diff --git a/src/index3.js b/src/index3.js
index 0cfbf08..e69de29 100644
--- a/src/index3.js
+++ b/src/index3.js
@@ -1 +0,0 @@
-2`

global.window = global; // trick
const files = require('react-diff-view/parse').parseDiff(diff);
console.log(files.length);
------------------------------------------------------------
~/Develop/test » node test.js                                                                                                               otakustay@Reinforce
3
```

For `@next` release I still get the same result, would you provide some more reproduce code?

**Comment by bobsilverberg** [comment]
I'm sorry, I'm no longer able to reproduce the problem. I don't know what I was doing earlier that was yielding that result, but when I try now I cannot reproduce it. Sorry for the noise.
