### ISSUE TITLE
Warning: Failed prop type: Invalid prop `children` supplied to `Diff`.

### ISSUE THREAD

**Issue by torhn** [otakustay/react-diff-view#35]
I'm using react-create-app and I'm getting this error while trying to show diff:
```
Warning: Failed prop type: Invalid prop `children` supplied to `Diff`.
```
I use the first example is the README Basic Usage
Data passed to Appdiff is a raw string containing output generated by git diff -U1.
Code used:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import {parseDiff, Diff, Hunk} from 'react-diff-view';

const Appdiff = ({diffText}) => {
    const files = parseDiff(diffText);

    const renderFile = ({oldRevision, newRevision, type, hunks}) => (
        <Diff key={oldRevision + '-' + newRevision} viewType="split" diffType={type} hunks={hunks}>
            {hunks => hunks.map(hunk => <Hunk key={hunk.content} hunk={hunk} />)}
        </Diff>
    );

    return (
        <div>
            {files.map(renderFile)}
        </div>
    );
};

class App extends Component {
  render() {
    const data = String.raw`diff --git outputs/1/test/tests.json outputs/2/test/tests.json
    --- outputs/1/test/tests.json	2019-02-14 09:26:27.769611562 +0100
    +++ outputs/2/test/tests.json	2019-02-14 09:25:12.288020243 +0100
    @@ -4,3 +4,3 @@
       "_route": "default",
    -  "_version": "1550132787",
    +  "_version": "1550132712",
       "json": {`;
    return (
      <div className="App">
        <header className="App-header">
          <Appdiff diffText={data}/>
        </header>
      </div>
    );
  }
}

export default App;
```

**Comment by otakustay** [comment]
You were referring to 2.x document while installed 1.x version, try to install `react-diff-view@next` to get the 2.x release, or find 1.x document here: https://github.com/otakustay/react-diff-view/tree/1.x

**Comment by torhn** [comment]
Ok my bad now I have the 2.x version. 
Warning is gone but nothing is showing on my page. 
Considering my code, what is the expected behaviour ?

**Comment by otakustay** [comment]
The issue is your git diff text is not a strictly valid one required by `parseDiff` function, this is a fixed version of the `App` component:

```jsx
class App extends Component {
    render() {
        const data = String.raw`diff --git outputs/1/test/tests.json outputs/2/test/tests.json
index dd7f55e..848285c 100644
--- outputs/1/test/tests.json	2019-02-14 09:26:27.769611562 +0100
+++ outputs/2/test/tests.json	2019-02-14 09:25:12.288020243 +0100
@@ -4,3 +4,3 @@
    "_route": "default",
-  "_version": "1550132787",
+  "_version": "1550132712",
    "json": {`;
        console.log(data);
        return (
            <div className="App">
                <header className="App-header">
                    <AppDiff diffText={data} />
                </header>
            </div>
        );
    }
}
```

I made two essential fixes:

1. Deleted leading whitespaces in each lines of `data` string.
2. Added a `index dd7f55e..848285c 100644` as the second line of `data` string, this is required for `parseDiff`, `dd7f55e` and `848285c` can be any value

**Comment by torhn** [comment]
Alright thanks I have an output now. But I think I still have a problem, it looks like the CSS is not loading.

![image](https://user-images.githubusercontent.com/38386685/52787833-6f5e7b00-305f-11e9-887c-cbcfdf379560.png)

**Comment by otakustay** [comment]
Yes CSS is extracted to a separate file:

```js
import 'react-diff-view/style/index.css';
```

**Comment by torhn** [comment]
Ok thanks looks better now but I still can't reproduce the same output as the example on the readme.
I don't have file name or anything:

![image](https://user-images.githubusercontent.com/38386685/52788251-a6815c00-3060-11e9-8f9f-3f85782393d9.png)

**Comment by otakustay** [comment]
Filenames and other information are not included in this package, we only provide the diff part, you may implement these component yourself like:

```
<div>
  <header>
    {filename}
  </head>
  <Diff ... />
</div>
```

The `Decoration` component can be used to extend the `<table>` element: https://github.com/otakustay/react-diff-view#add-decoration-around-hunks

In the `site` folder we have a very simple decoration: https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/HunkInfo.js

**Comment by torhn** [comment]
Ok. Could you tell me why is my diff text centered ?

**Comment by otakustay** [comment]
Possibly you have some styles in `App.css` which makes all text centered, could you provide more information to me? It seems you are not showing the actual code, for example in your provided image it is unified view however in your code you have `viewType="split"` specified

**Comment by torhn** [comment]
It was a conflict with App.css you were right.

I changed the code a bit between my first post so here it is:

```
import React, { Component } from 'react';
import {parseDiff, Diff, Hunk, Decoration} from 'react-diff-view';
import 'react-diff-view/style/index.css';

const Appdiff = ({diffText}) => {
    const files = parseDiff(diffText);

    const renderFile = ({oldRevision, newRevision, type, hunks}) => (
        <Diff key={oldRevision + '-' + newRevision} viewType="unified" diffType={type} hunks={hunks}>
            {hunks => hunks.map(hunk => [<Decoration key={"deco-" + hunk.content}>{hunk.content}></Decoration>,<Hunk key={hunk.content} hunk={hunk} />])}
        </Diff>
    );
    return (
        
        <div>
            {files.map(renderFile)}
        </div>
    );
};

class App extends Component {
  render() {
    const data = String.raw`diff --git a/requirements.txt b/requirements.txt
index c3f75dc..2cda10e 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -5,5 +5,5 @@ m3u8
 uvloop
 aiohttp
 cchardet
-aiodns
+aiodnstest
 graphitesender==0.11.1
diff --git a/run.sh b/run.sh
index afc32ae..9e430e1 100755
--- a/run.sh
+++ b/run.sh
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash

-BASEDIR=$(dirname "$0")
 VENV=$BASEDIR/.venv

 test -d "$VENV" || virtualenv -q "$VENV"
`;
    return (
      <div className="App">
        <Appdiff diffText={data}/>
      </div>
    );
  }
}
export default App;
```


Output is:

![image](https://user-images.githubusercontent.com/38386685/52791654-b6ea0480-3069-11e9-8c98-3a5b18a3fa63.png)

Here, 2 files are showed but there is not way to tell the filename from a hunk and to print it ? or separate the hunks maybe

**Comment by otakustay** [comment]
Created a sandbox based on your case: https://codesandbox.io/s/149oz0nw1q

Little changes to `renderFile` function with some extra CSS

**Comment by torhn** [comment]
That's perfect, thank you so much for your help and time, much appreciated !
