### ISSUE TITLE
Incorrect diff visualization

### ISSUE THREAD

**Issue by lazuka13** [otakustay/react-diff-view#44]
Hello
I believe I have encountered a bug in diff visualization
I used your example from here: https://github.com/otakustay/react-diff-view/tree/master/site and tried to visualize diff between two HTTP responses:
https://gist.github.com/lazuka13/12ad538b830ba9a5d344a3be646462e4
https://gist.github.com/lazuka13/572efa3b41e152fa1cd22167fd28dd14
And I got this visualization:
![image](https://user-images.githubusercontent.com/8972055/55867214-bc0b9180-5b8a-11e9-9ec4-fcd2acd357f7.png)

As you can see, modified X-Adfox was not shown at all, old X-Adfox header was not changed and X-Adfox-Debug header was duplicated. This output is the same for using your example in both modes - providing two texts or providing initial text and formatted diff.

Can you help me understand, what am I doing wrong or is there really a bug? If there is a bug, can you fix it?

**Comment by otakustay** [comment]
Seems a bug in git diff parser, I'll look into it this weekend

**Comment by otakustay** [comment]
After some debug I'm sure this bug lies in our diff apply function, could cause a little more time to fix

**Comment by otakustay** [comment]
Please try `2.1.1` which should fixed this issue, online demo is also updated

**Comment by lazuka13** [comment]
Hello again!
Version 2.1.1 did help me with previous case, but I encountered another problems with diff visualization:
Request: https://gist.github.com/lazuka13/2f51e5860c7465a086456727870659ba
Diff: https://gist.github.com/lazuka13/1e70edc0882affaf0ddf8d4adf393c92
Output: https://yadi.sk/d/11el4co_ZqtcwA
