### ISSUE TITLE
Bug in diff view

### ISSUE THREAD

**Issue by lazuka13** [otakustay/react-diff-view#45]
Hello again!
Version 2.1.1 did help me with previous case https://github.com/otakustay/react-diff-view/issues/44, but I have encountered another problems with diff visualization:
Request: https://gist.github.com/lazuka13/2f51e5860c7465a086456727870659ba
Diff: https://gist.github.com/lazuka13/1e70edc0882affaf0ddf8d4adf393c92
Output: https://yadi.sk/d/11el4co_ZqtcwA

**Comment by dancerphil** [comment]
It is not obvious to me. Would you like to describe the problem more in detail?

**Comment by lazuka13** [comment]
As you can see in calculated diff, "Content-Length" header has changed, but on screenshot there is no difference between two headers, although they are marked as having diff by color. Also on the second side you can see that response body starts at "eventBannerMoved" when it should start at "{"jsonapi":{"version":"1.0","meta""

**Comment by lazuka13** [comment]
And I tested this diff and source file with the example app provided in this repo - same results.

**Comment by otakustay** [comment]
This is a regression issue in `applydiff` function, we should consider the `lineNumber` property in that reduce call

**Comment by otakustay** [comment]
I have published `2.1.3`, tested cases in both #44 and #45 as well as some more complex diffs.

**Comment by otakustay** [comment]
Tokenization is a quite fragile feature currently and is very hard to unit test, if any issue  is encountered, feel free to open issue so we can fix it as soon as possible.
