### ISSUE TITLE
一个跑题的问题::>_<::

### ISSUE THREAD

**Issue by 132yse** [otakustay/react-diff-view#47]
那个，是这样的，之前一直在寻找国内的unpkg镜像，一直找不到
突然逛v2ex发现了您搞的 https://code.bdstatic.com/npm/

但是，不支持跨域::>_<::
```js
<script type="module">
  import {Eplayer} from 'https://code.bdstatic.com/npm/eplayer@1.3.15'

  customElements.define('e-player', Eplayer)
</script>
```
只有直接引用是没有同源策略的，type=module 类似的引用都是要跨域的

没地方反馈，只好来发 issue 啦
求大神看看能不能解决::>_<::

**Comment by otakustay** [comment]
仅有包名没有文件名的时候没有加上跨域头，你先写明文件名使用吧：

```html
<script type="module">
import {Eplayer} from 'https://code.bdstatic.com/npm/eplayer@1.3.15/packages/eplayer/index.js'

customElements.define('e-player', Eplayer)
</script>
```

有问题可以使用邮箱联系我，Github上应该能看到我邮箱

**Comment by 132yse** [comment]
> 仅有包名没有文件名的时候没有加上跨域头，你先写明文件名使用吧
谢啦，先凑合凑合2333
