### ISSUE TITLE
diffText 这个参数应该传什么？

### ISSUE THREAD

**Issue by Wangyage1** [otakustay/react-diff-view#50]
@diffText 这个参数应该传什么？
我想用在react项目中，想要输入两个字符串，然后输入比对结果的展示 ，应该怎么写？

**Comment by otakustay** [comment]
如果你有2个字符串要进行diff并且展示，可以参考这里：https://codesandbox.io/s/j7lwqj0l63

**Comment by Wangyage1** [comment]
感谢，问题已解决！
