### ISSUE TITLE
unidiff header vs git diff header

### ISSUE THREAD

**Issue by alexec** [otakustay/react-diff-view#53]
You can't use `unidiff` AFAIK. You must use `git diff`

```
diff --git a/test/fixture/test/ci.go b/test/fixture/test/ci.go
index 6829b8a2..4c565f1b 100644
--- a/test/fixture/test/ci.go
+++ b/test/fixture/test/ci.go
[CHANGES GO HERE]
```

unidiff format:

```
--- lao	2002-02-21 23:30:39.942229878 -0800
+++ tzu	2002-02-21 23:30:50.442260588 -0800
[CHANGES GO HERE]
```

**Comment by otakustay** [comment]
Yes currently we have only a git diff parser implemented. I'm not familiar to implement a parser so it is quite not possible to implement a unidiff parser according to the `Hunk` format.

However you can parse unidiff yourself, `Diff` component only requires a `hunks` prop to be rendered.

**Comment by alexec** [comment]
I also noted I would only get `file.type = 'modified'`. Add and delete are not recognized. Wasn't sure if I was doing this right thing?

**Comment by alexec** [comment]
Do you have an example of parsing unidiff?

**Comment by otakustay** [comment]
Could you provide me a complete unidiff text so I can try it?

**Comment by alexec** [comment]
https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html

**Comment by Neeraj-swarnkar** [comment]
Hi,

This library works fine , but when I am building I am getting this below error.

Unexpected token: name (t) [./~/unidiff/dist/index.js:1,12782]


ERROR in graphViews/ComplianceView.a597b349078d83afde42.js from UglifyJs
Unexpected token: name (t) [./~/unidiff/dist/index.js:1,12782][graphViews/ComplianceView.a597b349078d83afde42.js:27692,12739]


Can one of you please help ? Thanks.
