### ISSUE TITLE
StubHunk should not appear in new files or removed files

### ISSUE THREAD

**Issue by lijunbo1018** [otakustay/react-diff-view#6]
In cases of new file or removed file, there's no common content(change of type 'normal') exists, thus, stubHunk should not appear at the end of file.

**Comment by otakustay** [comment]
I dived into this issue and found it's unreasonable to implement in `parseDiff` function.

The `stubHunk` is a generic option which just means "we will add an empty hunk in the end of `hunks` array", this option does not specify the usage of the stub hunk, so if we just remove all stub hunks for add and delete files, it can cause issues when user tries to add other informations (such as the total size of a file, etc...) on the stub hunk header.

In this way, I'm not going to change this API and introduce breaking changes, it is better to map all parsed files and remove unnecessary stub hunks outside:

```js
import {parseDiff as parse} from 'react-diff-view';

const removeUnnecessaryStubHunk = file => {
    const {type, hunks} = file;

    if (type !== 'add' && type !== 'delete' && hunks.length === 1) {
        return {
            ...file,
            hunks: hunks.slice(0, -1)
        };
    }

    return file;
};

const parseDiff = diffText => parseDiff(diffText).map(removeUnnecessaryStubHunk);
```

I believe a diff wouldn't contain large amount of files (>= 100K for example), so this extra iteration will not hit performance.
