### ISSUE TITLE
getSelection behavior seems different on Safari

### ISSUE THREAD

**Issue by KevinHu2014** [otakustay/react-diff-view#62]
Hi,

Thank you so much for this library.

Recently found out that there's an different behavior on while selecting text on Safari.

### Chrome 
version: 76.0.3809.100
![Chrome](https://user-images.githubusercontent.com/7204070/62886467-c672ad80-bd6d-11e9-92dc-4126a37f650b.gif)

### Safari  
version: 12.1.2
![safari](https://user-images.githubusercontent.com/7204070/62886325-9d521d00-bd6d-11e9-9028-0d894cd8e558.gif)

## Steps to Reproduce
1. npm start (to see the demo)
2. type in some text to make the diff
3. select text in `Diff` area
3. see the different behavior between Safari and Chrome

## Detailed Description
On Safari, while selecting text in the `Diff` area. Both side of the text will be selected.

**Comment by otakustay** [comment]
Safari has bugs here, we can fix the visual selection by adding `-webkit-` to `user-select: none`, however copied content still contains unselected columns in safari, so I decide to not fix visual selection to prevent user confusion about copy & paste functionality

**Comment by KevinHu2014** [comment]
@otakustay  Thanks for fast response. Could you explain more detail on what kind of bug is happening on Safari ?

**Comment by otakustay** [comment]
@KevinHu2014 To reproduce this issue, I created a sandbox: https://codesandbox.io/s/friendly-feynman-1szfh

Reproduce steps are present in this sandbox, chrome and safari have different behavior when copying texts styled `user-select: none`.

**Comment by otakustay** [comment]
We can fix this by adding an extra element indicated in this thread: https://stackoverflow.com/questions/47250505/text-of-element-with-css-user-select-none-gets-copied-if-it-is-located-between, but this is way too performance unfriendly and I wouldn't involve this solution before the last minute.

**Comment by KevinHu2014** [comment]
Will this help?  sandbox: [https://codesandbox.io/s/busy-fermi-1l0vw](https://codesandbox.io/s/busy-fermi-1l0vw)
By nesting the table, but this way seems also performance unfriendly.

**Comment by otakustay** [comment]
This can simply solve the copy & paste issue, but this will cause an extreme performance dropdown since it involves multiple table layouts, also it could probably incompatible with customizations such as `widgets`, `renderGutter` and `Decoration`, I mostly will not use this fix.
