### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isNormal' of undefined

### ISSUE THREAD

**Issue by ice-zjchen** [otakustay/react-diff-view#63]
### 1. 重现过程：
**ORIGINAL SOURCE CODE**
<pre>
```
## 新增分享

**接口描述**

相同主体下的账户分享指定资产。

**接口URL**

`http://sem.baidubce.com/v1/feed/cloud/AssetShareFeedService/addAssetShareFeed`

**请求参数说明**

资产分享请求参数为资产分享请求对象数组，最大长度10。
资产分享请求对象字段说明：

| 字段名称       | 类型     | 描述                 |
| ---------- | ------ | ------------------ |
| srcAssetId   | number | 分享的资产id              |
| toUserId  | number | 分享的userid              |
| type   | number | 分享的资产类型：0表示视频    |

**响应参数说明**

响应为资产分享对象，字段说明如下：

| 字段名称       | 类型     | 描述                 |
| ---------- | ------ | ------------------ |
| srcAssetId   | number | 分享的资产id              |
| toUserId  | number | 分享的userid              |
| type   | number | 分享的资产类型：0表示视频    |
| assetId     | number | 分享后的资产id |
| assetName     | string | 资产名称     |
| assetContent        | string | 分享类型为视频时表示新的视频url          |

响应结果中的对象与请求参数中一一对应（其中失败的不会包含在data中，但会在error中提供错误信息）

**请求示例**

```javascript
POST /v1/feed/cloud/AssetShareFeedService/addAssetShareFeed HTTP/1.1
Accept-encoding: 'gzip, deflate'
Host: sem.baidubce.com
ContentType: application/json
Authorization: bce-auth-v1/b406c344bb764e00aff7d3b80d9bd87a/2019-06-05T07:34:31Z/1800/host/bb0f820e4499b8b44548388b37a7afed970e965a7a59f79ebac47a99c315a97b(签名有效时间为30分钟，需要替换成自己生成的签名)
Accept: '*/*'
{
    "header": {
        "opUsername": "example",
        "tgUsername": "example",
        "bceUser": "example",
        "opPassword": "example",
        "tgPassword": "example"
    },
    "body": [
        {
            "srcAssetId":2333,
            "toUserId":3333,
            "type":0
        }
    ]
}
```

**响应示例**

```javascript
{
    "body": {
        "data": [
            {
                "srcAssetId":2333,
                "toUserId":3333,
                "type":0,
                "assetId":2334,
                "assetName":"视频_副本",
                "assetContent": "http://fctestvideo.cdn.bcebos.com/e843c89e836065713afcacbe5de89c90.mp4"
            }
        ]
    },
    "header": {
        "oprs": 1,
        "failures": [],
        "succ": 1,
        "oprtime": 0,
        "desc": "success",
        "status": 0
    }
}
```
</pre>

**DIFF TEXT**
<pre>
--- a/home/work/doc-cms-backend/bin/temp/e3217f43-04dd-4ec3-9f1e-0a81da9c9a27
+++ b/home/work/doc-cms-backend/bin/temp/548cf91d-e57d-4efa-8360-91800e635f5d
@@ -10,14 +10,17 @@
 
 **请求参数说明**
 
-资产分享请求参数为资产分享请求对象数组，最大长度10。
+资产分享请求参数为资产分享请求对象数组，视频分享最多支持给10个userid分享10个视频资产，自定义人群包分享最多支持给1个userid分享10个人群包。
+
+支持分享的自定义人群包类型：idfa、imei、手机号md5、idfa_md5、imei_md5、id上传相似人群、账户历史人群、账户历史人群相似人群；未生效人群包不支持分享；不支持二次分享。
+
 资产分享请求对象字段说明：
 
 | 字段名称       | 类型     | 描述                 |
 | ---------- | ------ | ------------------ |
 | srcAssetId   | number | 分享的资产id              |
 | toUserId  | number | 分享的userid              |
-| type   | number | 分享的资产类型：0表示视频    |
+| type   | number | 分享的资产类型：0表示视频，1表示自定义人群包    |
 
 **响应参数说明**
 
@@ -27,10 +30,10 @@
 | ---------- | ------ | ------------------ |
 | srcAssetId   | number | 分享的资产id              |
 | toUserId  | number | 分享的userid              |
-| type   | number | 分享的资产类型：0表示视频    |
+| type   | number | 分享的资产类型：0表示视频，1表示自定义人群包    |
 | assetId     | number | 分享后的资产id |
 | assetName     | string | 资产名称     |
-| assetContent        | string | 分享类型为视频时表示新的视频url          |
+| assetContent        | string | 分享类型为视频时表示新的视频url，分享类型为自定义人群包时不返回          |
 
 响应结果中的对象与请求参数中一一对应（其中失败的不会包含在data中，但会在error中提供错误信息）
</pre>

**点击红框进行展开**
![image](https://user-images.githubusercontent.com/2605406/63279205-2ff93b80-c2db-11e9-9b39-8320d93284a5.png)

### 2. 报错内容
![image](https://user-images.githubusercontent.com/2605406/63279445-93836900-c2db-11e9-9ac9-d23b2fd17e5d.png)
**简单debug**

![image](https://user-images.githubusercontent.com/2605406/63279612-dfcea900-c2db-11e9-93ea-171a899e27ad.png)

**Comment by otakustay** [comment]
这个diff的输入不对，最后一个hunk中的

```
@@ -27,10 +30,10 @@
```

声明“左侧从27行开始，一共10行；右侧从30行开始，一共10行”，但从后面的内容来看，左右均只有9行，因此在展开时的起始位置就会出错

应该是获取git diff时某个环节做了`trim()`的操作，导致最后的空行和空格都没了
