### ISSUE TITLE
Feature: Ability to hide whitespace changes

### ISSUE THREAD

**Issue by slavikdenis** [otakustay/react-diff-view#65]
I was thinking if it would be possible to add an option to the diff view to hide whitespace changes like https://github.blog/2018-05-01-ignore-white-space-in-code-review/ .

So for example, here, most of the changes would be redundant:
![image](https://user-images.githubusercontent.com/15640932/65672581-921b2e00-e049-11e9-9c28-98b96a8054d3.png)

Thanks

**Comment by otakustay** [comment]
Currently, without inventing a complex diff algorithm, it is possible to "visually hide" spaces with a little performance loss.

![image](https://user-images.githubusercontent.com/639549/65675403-b9412200-e080-11e9-8a10-156f29da3047.png)


This can be archived by our tokenization system and the [pickRanges](https://github.com/otakustay/react-diff-view#pick-ranges) function:

1. Flatten hunks to get all changes
2. For each change, inspect the leading and trailing whitespace count
3. Create a leading and trailing `range` object if there is any whitespace there
4. Collect all ranges and call `pickRanges` in `enhancers` of `tokenize` options

I've created a sandbox to demonstrate this case: https://codesandbox.io/s/react-diff-view-mark-edits-demo-8ndcl

The key implementation is `pickLeadingAndTrailingSpaces` function in `tokenize.js` and `renderToken` function in `index.js`

**Comment by slavikdenis** [comment]
@otakustay thanks, helped a lot :)

**Comment by slavikdenis** [comment]
@otakustay Run into another problem.

Do you think it would be doable to show only the first line from comparing 'old' and 'new' (different spacing)?

old:
```
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
```

new:
```
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
```

Current results from the provided sandbox:
![image](https://user-images.githubusercontent.com/15640932/66709377-2b915200-ed63-11e9-993e-c5ca35022072.png)

Wanted result:
![image](https://user-images.githubusercontent.com/15640932/66709382-3fd54f00-ed63-11e9-820a-662cd42deaa4.png)


Thank you for your help so far

**Comment by otakustay** [comment]
You are expecting a different behavior from the original git diff, in you screenshots a 3 line diff becomes a single line one, in order to make it work we should modify the diff text (or hunks), this can be done by iterating through `changes` in each hunk, finding those with only space differences

I'd like to think it as a pure data structure modification problem, not something related to presentation.

This is complex, I don't recommend you to do this, we can expect something like:

```js
const hunks = parseDiff(diffText, {nearbySequences: 'zip'});

const onlySpaceDiff = (x, y, stop = false) => {
    const index = x.indexOf(y);
    if (index >= 0) {
        const leftPadding = x.slice(0, index);
        const rightPadding = x.slice(index + y.length);
        const spaceOnly = /^\s*$/;
        if (spaceOnly.test(leftPadding) && spaceOnly.test(rightPadding)) {
            return true;
        }
    }
    return stop ? false : onlySpaceDiff(y, x, true);
};

const removeUnwantedChanges = hunk => {
    let hasSpaceDifferenceOccured = false;
    const needRemove = new Set();

    for (let i = 0; i < hunk.changes.length; i++) {
        const currentChange = hunk.changes[i];
        const previousChange = hunk.changes[i - 1];
        
        // The first line should neve be omitted
        if (!previousChange) {
            continue;
        }

        // A delete and insert pair indicates a modification of a line
        if (previousChange.isDelete && currentChange.isInsert && onlySpaceDiff(previousChange.content, currentChange.content)) {
            // Only remove them from diff after the first diff line
            if (hasSpaceDifferenceOccured) {
                needRemove.add(previousChange);
                needRemove.add(currentChange);
            }
            else {
                hasSpaceDifferenceOccured = true;
            }
        }
    }

    hunk.changes = hunk.changes.filter(c => !needRemove.has(c));
    // However we need to:
    // 1. fix the hunk.content, hunk.newLines, hunk.oldLines, hunk.newStart, hunk.oldStart property to match changes
    // 2. detect if removal of changes can cause a hunk splitting into 2 or more parts
}
```

The comment part is the key of complexity, I'm not confident that I can deal with it 😭

**Comment by slavikdenis** [comment]
I think, at this point, its just better to generate the diff with whitespace changes off, because this seems like an overkill or react-diff-view library. Thank you for your time

**Comment by viralmodi** [comment]
@slavikdenis @otakustay We are planning to use this library and need this feature too. What was the conclusion on this? Here is the requirement: The whitespace changes should be visible when user selects that option and they along with the entire line should be removed from the diff when user opts to hide whitespace changes if the only diff on the line were whitespaces (just leading and trailing whitespaces will do). If this is not already supported, can you give us a code snippet/way to incorporate this into your component and be able to use it for our use-case?

**Comment by otakustay** [comment]
The best way is to generate diff with whitespace ignored, like `git diff`'s `-b` option described as [this article](https://coderwall.com/p/crj69a/from-a-useless-git-diff-to-a-useful-one)

Once a diff is generated, it is really hard to modify it to exclude whitespaces, a possible way is to visually hide them by adding `visibility: hidden` to leading and trailing spaces, if you can accept this, I could create a sandbox demo
