### ISSUE TITLE
expose hooks from index

### ISSUE THREAD

**Issue by dancerphil** [otakustay/react-diff-view#69]
Trying to replace `withTokenizeWorker` with `useTokenizeWorker`, but it is not exported yet.

**Comment by otakustay** [comment]
[Recent commits](https://github.com/otakustay/react-diff-view/commit/58525c9b47f12f1e54aecbc3792813df8ea02f45) already did this, will publish a new version after some tests.

**Comment by otakustay** [comment]
See version 2.3.0
