### ISSUE TITLE
GutterEvents and codeEvents click events have no effect in version1.8.0

### ISSUE THREAD

**Issue by mmryzmr** [otakustay/react-diff-view#72]
this.state = {
      selectedChanges: [],
      gutterEvents: {
        onClick: this.selectChange.bind(this)
      },
      codeEvents: {
        onClick: this.selectChange.bind(this)
      }
    };
const {gutterEvents, codeEvents} = this.state;
    const hunkProps = {gutterEvents, codeEvents};
<Diff key={`${oldRevision}-${newRevision}`} viewType="split" diffType={type} >
            {hunks.map(hunk => <Hunk key={hunk.content}  hunk={hunk} {...hunkProps}/>)}
          </Diff>

**Comment by dancerphil** [comment]
Which version of document are you looking into?

The current README introduces the api of react-diff-view@2.4.1

**Comment by otakustay** [comment]
I've created a sandbox to try events: https://codesandbox.io/s/react-diff-view70-b5s02

It seems to work as expected

**Comment by dancerphil** [comment]
The sandbox use react-diff-view@2.2.0, which works.

I remember event api breaks in react-diff-view@2.0.0.

See [Doc for 1.8.0](https://github.com/otakustay/react-diff-view/tree/v1.8.0) for more.

**Comment by mmryzmr** [comment]
Hello, is there any specific example about expand folding code? I get an error when using HunkHeader (I use version 1.8)

**Comment by dancerphil** [comment]
You can see the demo in the link above.

**Comment by dancerphil** [comment]
I highly recommend you to update to the latest version.

**Comment by otakustay** [comment]
According to [1.x README](https://github.com/otakustay/react-diff-view/tree/1.x), all events are set via `customEvents` prop from `Diff` component.

I've updated sandbox to illustrate this in 1.x version: https://codesandbox.io/s/react-diff-view72-b5s02

Still I recommend to upgrade to 2.x, which ships with a [useSourceExpansion](https://github.com/otakustay/react-diff-view/blob/master/src/hooks/useSourceExpansion.js) hook to help you expand code with ease.
