### ISSUE TITLE
getChangeKey function should include the file/revision 

### ISSUE THREAD

**Issue by siddhant1** [otakustay/react-diff-view#76]
getChangeKey function should contain the file/revision to make it unique across different files.

For example, I need to render a widget but I have different files, now I need to render a widget for example on line 9 which is inserted, the key will be I9, now the widget will be rendered on every line with the key I9 in each file , so I think we should make the widgets and the getChangeKey function file/revision dependent.
Is there any way out this with the current implementation?

**Comment by otakustay** [comment]
`Diff` component isn't aware of any file related information like filename or revision, the revision is a special term from version control system like git or svn, but diff is a more common term, we can generate a diff from any text without a svn or git, even without a filename

When you need a filename or revision to specify something, you have to manage those information yourself and concat them with the change key:

```js
const FileDiff = ({filename, revision, hunks, onAddComment}) => {
    const addComment = useCallback(
        ({change}) => {
            const key = `${filename}-${revision}-${getChangeKey(change)}`;
            onAddComment(key);
        },
        [filename, revision, onAddComment]
    );
    const gutterEvents = {onClick: addComment};

    return (
        <Diff hunks={hunks}>
            {hunks => hunks.map(h => <Hunk key={h.content} hunk={h} gutterEvents={gutterEvents} />)}
        </Diff>
    );
};
```

**Comment by siddhant1** [comment]
Makes sense thanks!

**Comment by siddhant1** [comment]
also @otakustay do you have a sandbox where you got the syntax highlighting working?

**Comment by otakustay** [comment]
I don't have an existing sandbox, but it is not complex, in order to make syntax highlighting work, you need to install [refractor](https://www.npmjs.com/package/refractor)

```js
import * as refractor from 'refractor';
import {tokenize} from 'react-diff-view';

// after you get hunks
const tokens = useMemo(
    () => {
        const options = {
            refractor,
            highlight: true,
            language: 'javascript', // any language refractor supports
            oldSource: source, // old version of source code, if any, optional
        };

        return tokenize(hunks, options);
    },
    [hunks]
);

<Diff tokens={tokens} {...otherProps}>
    ...
</Diff>
```

Syntax highlighted theme can be installed via [prism-themes](https://www.npmjs.com/package/prism-themes)

```js
import 'prism-themes/themes/prism-vs.css';
```

**Comment by siddhant1** [comment]
what is the hunks variable? is it an array of all the hunks from all the files?
