### ISSUE TITLE
Make gutters accesible by using hrefs (tabbale by default)

### ISSUE THREAD

**Issue by siddhant1** [otakustay/react-diff-view#79]

**Comment by otakustay** [comment]
Introducing `tabindex` to gutter element could be breaking since it may conflicts with user's tab order, I'd like to suggest implement via `renderGutter` prop:

```jsx
const renderGutter = ({renderDefault}) => <span tabIndex="0">{renderDefault()}</span>

<Diff renderGutter={renderGutter} />
```

Also feel free to change `span` to `a` so you can have a `href` attribute generated from any algorithm
