### ISSUE TITLE
File path (oldPath/newPath) returned by parseDiff gets distorted if whitespace exists

### ISSUE THREAD

**Issue by ahsan-ih** [otakustay/react-diff-view#80]
If the filename has white space in it, then the returned files from parseDiff show incorrect old and new paths.

here's the result for a file with name "RFM69HCW_BOB copy.s#1"

diff --git a/RFM69HCW_BOB copy.s#1 b/RFM69HCW_BOB copy.s#1
index 353db1e..379af71 100644
--- a/RFM69HCW_BOB copy.s#1	
+++ b/RFM69HCW_BOB copy.s#1	
@@ -1,9 +1,10 @@

<img width="340" alt="Screen Shot" src="https://user-images.githubusercontent.com/56548120/76404433-49152700-63a8-11ea-96a9-614d252dfc3f.png">

**Comment by dancerphil** [comment]
I think it may be a bug in `gitdiff-parser` since it splits with whitespace.

The correct way maybe check the string after `---` & `+++`.

We will have some test to figure out.

**Comment by ahsan-ih** [comment]
Is there any other way I could get the filename?

**Comment by dancerphil** [comment]
The only way I can think of is to use the regex to match the filename in diff for now.

But it has potential risks since we haven't test it yet.

See https://git-scm.com/docs/git-diff#_generating_patch_text_with_p for more.

@otakustay , do you have any ideas?

**Comment by dancerphil** [comment]
```suggestion
            while (i < linesLen) {
                var line = lines[i];

                if (line.indexOf('diff --git') === 0) {
+                   /* new start */
+                   var match = /^diff --git a\/(.*) b\/(.*)$/.exec(line);
+                   var oldPath = match[1];
+                   var newPath = match[2];
+                   /* new end */
-                   /* old start */
-                   var filesStr = line.slice(11);
-                   var oldPath = null;
-                   var newPath = null;
-
-                   var quoteIndex = filesStr.indexOf('"');
-                   switch (quoteIndex) {
-                       case -1:
-                           var segs = filesStr.split(' ');
-                           oldPath = segs[0].slice(2);
-                           newPath = segs[1].slice(2);
-                           break;
-
-                       case 0:
-                           var nextQuoteIndex = filesStr.indexOf('"', 2);
-                           oldPath = filesStr.slice(3, nextQuoteIndex);
-                           var newQuoteIndex = filesStr.indexOf('"', nextQuoteIndex + 1);
-                           if (newQuoteIndex < 0) {
-                               newPath = filesStr.slice(nextQuoteIndex + 4);
-                           }
-                           else {
-                               newPath = filesStr.slice(newQuoteIndex + 3, -1);
-                           }
-                           break;
-
-                       default:
-                           var segs = filesStr.split(' ');
-                           oldPath = segs[0].slice(2);
-                           newPath = segs[1].slice(3, -1);
-                           break;
-                   }
-                   /* old end */
```

We should let eric to review this, there must be some usage I don't know.

**Comment by otakustay** [comment]
Seems better to extract filenames from `---` and `+++` lines.

If we have to get filename from the first line, we should do a look-ahead parse to find the last ` b/` segment as a split point.

I'll discuss this with Erik tomorrow

**Comment by otakustay** [comment]
Update: Erik will fix this issue and publish a new version of `gitdiff-parser` recently

**Comment by otakustay** [comment]
I'm testing a new version of `gitdiff-parser` but seems that it is more strict in diff format, we have to re-implement the `normalizeDiffText` function to work with simple unidiff, and some of our test snapshots are incorrect at the very beginning

**Comment by otakustay** [comment]
`2.4.2` should have fixed this issue

**Comment by ahsan-ih** [comment]
@otakustay I am still getting the same result with 2.4.2.
Even tried removing node_modules and lock files and installed everything from scratch again.

**Comment by otakustay** [comment]
It seems in last publish I forget to have a clean yarn install, please try `2.4.3`

![image](https://user-images.githubusercontent.com/639549/77036562-62daed80-69ea-11ea-9ef4-a6ccba8d55ea.png)

**Comment by ahsan-ih** [comment]
Works fine now. Thanks a bunch 👍

**Comment by jclem** [comment]
This bug appears to be back as of react-diff-view 3.2.1 and [is still in gitdiff-parser](https://github.com/ecomfe/gitdiff-parser/issues/34).

**Comment by doanvalerie** [comment]
> This bug appears to be back as of react-diff-view 3.2.1 and [is still in gitdiff-parser](https://github.com/ecomfe/gitdiff-parser/issues/34).

I am facing this issue as well in version 3.3.3. Are there any updates for a fix for this?
