### ISSUE TITLE
请问有展示Split view 图片中实现的文件名展示以及添加comment的demo嘛

### ISSUE THREAD

**Issue by lunalusy** [otakustay/react-diff-view#84]

**Comment by otakustay** [comment]
我做了一个简单的示例：https://codesandbox.io/s/nifty-herschel-3w9s8

数据用了写死的，没有后端

做comment的关键是维护一个`{changeKey: widget}`的字典，widget是任意的元素，在示例里我用`useWidgets`这个hook去实现，先维护一系列的对象，然后再用`mapValues`把它变成react元素

单击行号就可以添加评论，通过`renderGutter`让行号在hover的时候变成+号（可选），然后用`gutterEvents`添加`onClick`事件来实现功能

如果要连接后端，差不多就是在`useWidgets`里处理，比如在`submit`中请求后端再处理数组

**Comment by lunalusy** [comment]
明白了，非常感谢

**Comment by lunalusy** [comment]
明白了，非常感谢
