### ISSUE TITLE
path 解析问题

### ISSUE THREAD

**Issue by lunalusy** [otakustay/react-diff-view#85]
![image](https://user-images.githubusercontent.com/33686292/78650144-16037c00-78f1-11ea-89f4-577a919db212.png)

使用git diff，解析出来的文件名缺少2个字符位置，使用的是2.4.3版本的react-diff-review
请问是我哪里处理的不对，还是什么原因啊？

**Comment by otakustay** [comment]
你是指缺了a/和b/吗，这两东西本来就不是文件名，是git diff的标记占位符

**Comment by lunalusy** [comment]
哦哦，知道原因了，非常感谢
