### ISSUE TITLE
展示问题

### ISSUE THREAD

**Issue by lunalusy** [otakustay/react-diff-view#86]
![image](https://user-images.githubusercontent.com/33686292/78677118-e9178f00-7919-11ea-9f8c-c74a41da65f7.png)
请问能像上面一样，能在diff code前面加+/-标识嘛

**Comment by otakustay** [comment]
这个最简单的就是写个css，这些个td元素只有class的，diff-code-inserr之类的，然后用::before

**Comment by lunalusy** [comment]
好哒，问问有没有这个的勾子

**Comment by lunalusy** [comment]
非常感谢

**Comment by otakustay** [comment]
理论上，因为整个组件的高亮是一个完全开放的模式，就是文档里的[Token system](https://github.com/otakustay/react-diff-view#token-system)这一块，通过这个往每一行前面插一个符号是可以做到的，但只插一个固定的内容太简单了，用CSS显然是一个更为低成本的方法。如果要插入动态的，更复杂的内容，走Token system是可以的

**Comment by pccai** [comment]
.diff-code-insert::before{
    content:'+';
}
.diff-code-delete::before{
    content:'-';
}
.diff-code-normal::before{
    content:' ';
}
