### ISSUE TITLE
Only show added lines?

### ISSUE THREAD

**Issue by grantspilsbury** [otakustay/react-diff-view#87]
I have a view that I want to either highlight added OR removed lines, but not both at the same time.

Is there a way to diff for ONLY added lines OR removed lines. I don't want to show them at the same time. 

Is it possible to return only 1 side of the side-by-side view?
Is it possible to only highlight added lines in the unified view?

**Comment by otakustay** [comment]
The simpliest way is to use unified view and add these css to exclude insert changes:

```css
.diff-gutter-insert,
.diff-code-insert {
    display: none;
}
```

Use `.diff-gutter-delete, diff-code-delete` to exclude delete changes.

However this does not change render performance at all, once you need a faster render excluding some changes, you could simple modify `hunk.changes` in each hunk object, filtering out those unwanted.
