### ISSUE TITLE
Does it support both word diff and line diff highligiting?

### ISSUE THREAD

**Issue by paul777888** [otakustay/react-diff-view#88]
I see it highlights a line for xml file compare, but not seeing word diff highlighting within a line.

**Comment by paul777888** [comment]
<img width="1430" alt="Screen Shot 2020-04-20 at 1 13 32 PM" src="https://user-images.githubusercontent.com/4109510/79779825-fd3f9100-8308-11ea-8a4a-cd0e93e258af.png">

**Comment by otakustay** [comment]
Please refer to [this sandbox](https://codesandbox.io/s/kkj0o16xrv) to enable word diff

1. Use `tokenize` function and `markEdits` to generate tokens from hunks
2. Pass `tokens` to `Diff` component

Highlight also works by adding `refractor` package and changing `options` to:

```
import refractor from 'refractor';

const options = {
  highlight: true,
  refractor: refractor,
  enhancers: [...]
};
```

**Comment by paul777888** [comment]
Nice, I can see value highlighting now.

Is it possible to make both side scrollable when doing side-by-side?

**Comment by otakustay** [comment]
No, side-by-side diff is rendered using a single table, it is impossible to make each side scroll independently
