### ISSUE TITLE
Parse yet another unidff format

### ISSUE THREAD

**Issue by dufferzafar** [otakustay/react-diff-view#94]
On the backend, I'm generating diff using [python's difflib](https://docs.python.org/3/library/difflib.html#difflib.unified_diff) module. Which diffs that look like:

```
--- cn=Filled,ou=random,dc=infra
+++ cn=Filled,ou=random,dc=infra
@@ -2,5 +2,5 @@
 cn: Filled
 moduleName: filled
 mode: on
-value: 1300.0
+value: 1400.0
 tickerList: ['RANDOM']
```

Which when parsed result in oldPath, newPath etc. being empty.

The issue is here: https://github.com/otakustay/react-diff-view/blob/02b1f538d18d21bb6cf0762b9003c23cb53d13a9/src/utils/parse.js#L65

I think you should just pickup the 1st element rather than the slice?

**Comment by otakustay** [comment]
It's OK for me to support various diff format, but I don't quite have enough time to ship it quickly, you can create a PR if you need it ASAP, or you may wait for about 1 month
