### ISSUE TITLE
I wanted to use the lazy loading, Can I achieve this ?

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [otakustay/react-diff-view#95]
I know this library supports the large diff lazy loading, 

I have a code sand box where I am using the library 
https://codesandbox.io/s/react-diff-view-demo-4jv9h

But when i have very big files and it need to diff and show page hangs,
How to implement lazy loading or display chunks of data and load more on scroll, something we can achieve..

You can update my sandbox to guide me. thanks..

**Comment by Neeraj-swarnkar** [comment]
@otakustay Could you help me here ? Thanks..

**Comment by otakustay** [comment]
How big is your diff? You can copy that diff here so we can use it to locate the performance issue and have a more accurate solution.

If the diff parse takes a long time, the best solution is to put it in a web worker for async parse.

If the render is slow, it is possible to create a virtual list to render hunks, however it is more complicated and is not supported directly, we have to modify `hunks` to archive this

**Comment by Neeraj-swarnkar** [comment]
> How big is your diff? You can copy that diff here so we can use it to locate the performance issue and have a more accurate solution.
> 
> If the diff parse takes a long time, the best solution is to put it in a web worker for async parse.
> 
> If the render is slow, it is possible to create a virtual list to render hunks, however it is more complicated and is not supported directly, we have to modify `hunks` to archive this

I have a code sand box where I am using the library - 
https://codesandbox.io/s/react-diff-view-demo-4jv9h
Without web workers can we do that,

Total number of lines is 100K and when we compare there diff data which takes almost 4-5 mins,

**Comment by otakustay** [comment]
I have investigated your sandbox, however I really need your 100K diff to exactly reproduce this issue in order to give you an accurate solution

**Comment by Neeraj-swarnkar** [comment]
> I have investigated your sandbox, however I really need your 100K diff to exactly reproduce this issue in order to give you an accurate solution

Sure, Let me create the sandbox with that, I will share with you.
Thanks..
