### ISSUE TITLE
hightlight=true,css in js 解析问题

### ISSUE THREAD

**Issue by lunalusy** [otakustay/react-diff-view#98]
const options = {
      highlight: true,
      oldSource,
      language: codeType,
      refractor,
      enhancers: [markEdits(hunksWithSourceExpanded, { type: 'line' })],
    };
    const tokenizedResult = tokenize(hunksWithSourceExpanded, options);
这样的写法，使用styled-component定义的样式解析出来不对
 ${hiDPI(1.5)} {
     ___CSS_1___
        }
       ___CSS_2___ {
           ___CSS_3___
          }
            ___CSS_4___ {
               ___CSS_5___
             }
             ___CSS_6___ {
                 ___CSS_7___

highlight=false，解析就是正确的，但是没有高亮

${hiDPI(1.5)} {
--
 ${content(.75, 1.5)}
  ${hiDPI(2)} {
      ${content(.5, 2)}
           ${hiDPI(2.75)} {
               ${content(.36363636, 2.75)}
                ${hiDPI(3)} {
                  ${content(.33333333, 3)}
           }

请问是我哪里写法有问题嘛，还有，语法高亮是需要手动引入语法高亮样式库嘛？
发现手动import 'prismjs/themes/prism-coy.css';，hightlight=true是有语法高亮的

const options = {
      highlight: true,
      oldSource,
      language: codeType,
      // refractor,
      enhancers: [markEdits(hunksWithSourceExpanded, { type: 'line' })],
    };
如果不引入refractor，会报 Cannot read property 'highlight' of undefined的错

**Comment by otakustay** [comment]
@dancerphil 这个事情是不是`refractor`的BUG？
