### ISSUE TITLE
有中文文档吗

### ISSUE THREAD

**Issue by Lcj-space** [otakustay/react-diff-view#99]

**Comment by Lcj-space** [comment]
git 对比有左侧目录的树状结构怎么显示

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/85376394-39da7380-b56a-11ea-9832-536b806ef3a1.png)

**Comment by otakustay** [comment]
这个组件只负责展示一个文件的代码diff的部分，并不是一个完事的github diff功能的实现

文件树你得自己实现一把，比如用antd的Tree组件，或者用[react-infinite-tree](https://www.npmjs.com/package/react-infinite-tree)做个性能更好的

**Comment by Lcj-space** [comment]
> 这个组件只负责展示一个文件的代码diff的部分，并不是一个完事的github diff功能的实现
> 
> 文件树你得自己实现一把，比如用antd的Tree组件，或者用[react-infinite-tree](https://www.npmjs.com/package/react-infinite-tree)做个性能更好的

好的谢谢，还有一个问题我想知道如何收起相同部分的代码。

**Comment by otakustay** [comment]
一般git的diff会生成3行相同的代码，一个办法是生成diff的时候用`git diff --unified=0`把相同行干掉

第二个方案是在`parse`以后，遍历每个`hunk.changes`然后把里面`type === 'normal'`的`change`删掉，就不会有相同行了

如果你不仅仅是想要他们消失，而是要实现用户点个啥按钮可以收起展开，那你得按照第二个方案，生成一个删了normal change的，一个没删的，来回替换

**Comment by Lcj-space** [comment]
> 一般git的diff会生成3行相同的代码，一个办法是生成diff的时候用`git diff --unified=0`把相同行干掉
> 
> 第二个方案是在`parse`以后，遍历每个`hunk.changes`然后把里面`type === 'normal'`的`change`删掉，就不会有相同行了
> 
> 如果你不仅仅是想要他们消失，而是要实现用户点个啥按钮可以收起展开，那你得按照第二个方案，生成一个删了normal change的，一个没删的，来回替换

好的，明白了。非常感谢。我需要的场景就是你说的第二种。

**Comment by otakustay** [comment]
想了一想，没这么简单，如果把normal的行删掉，会涉及到`oldStart`、`oldLines`、`newStart`、`newLines`变化，也有可能2个变化的行中间夹着一些相同的行，这个时候一个hunk就要拆成2个了

这个逻辑能实现，但并不简单，老实说没有相同行并不好看……你实在要的话我明天试试能不能写出来

**Comment by Lcj-space** [comment]
> 想了一想，没这么简单，如果把normal的行删掉，会涉及到`oldStart`、`oldLines`、`newStart`、`newLines`变化，也有可能2个变化的行中间夹着一些相同的行，这个时候一个hunk就要拆成2个了
> 
> 这个逻辑能实现，但并不简单，老实说没有相同行并不好看……你实在要的话我明天试试能不能写出来

![image](https://user-images.githubusercontent.com/22415092/85408987-cf402c80-b597-11ea-9380-0bc8f8280cd8.png)
其实就是想要 gitlab 上面的功能，我这个截图上面红框圈出的应该就是把相同行收起吧

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/85409323-407fdf80-b598-11ea-8f46-ce0d6f4b579d.png)
我看你的文档上的图是不是已经实现这个功能了

**Comment by otakustay** [comment]
github这个就是你可以一个按钮展开（其实再收起也行）

这个功能可能比你想象的还复杂一些，正常的diff里最多只有上下3行的相同行，为了能完整地展开更多的行，你需要左边代码的源文件（加上diff算出右边代码），然后有一大堆的逻辑

这个逻辑我已经通过几个hook提供了，比如[useSourceExpansion](https://github.com/otakustay/react-diff-view/blob/master/src/hooks/useSourceExpansion.js)就是干这个的，但文档确实不完善

你真的需要这个展开源码的功能的话，明天抽时间写个demo给你……

其实你要完整实现github的效果，远不止这些：

1. 代码高亮
2. 展开相同行
3. 行可以选中，甚至可以选择多行，并会在URL中表现出来
4. 代码上有引用跳转，点个函数名可以跳到定义
5. 能添加评论

这些功能基于这个组件都能实现，就是要在外层加逻辑（各种变着法的折腾`hunks`数组）。我们内部使用就有全部这些能力，另外还有在行号前面显示单元测试覆盖之类的……

**Comment by Lcj-space** [comment]
> github这个就是你可以一个按钮展开（其实再收起也行）
> 
> 这个功能可能比你想象的还复杂一些，正常的diff里最多只有上下3行的相同行，为了能完整地展开更多的行，你需要左边代码的源文件（加上diff算出右边代码），然后有一大堆的逻辑
> 
> 这个逻辑我已经通过几个hook提供了，比如[useSourceExpansion](https://github.com/otakustay/react-diff-view/blob/master/src/hooks/useSourceExpansion.js)就是干这个的，但文档确实不完善
> 
> 你真的需要这个展开源码的功能的话，明天抽时间写个demo给你……
> 
> 其实你要完整实现github的效果，远不止这些：
> 
> 1. 代码高亮
> 2. 展开相同行
> 3. 行可以选中，甚至可以选择多行，并会在URL中表现出来
> 4. 代码上有引用跳转，点个函数名可以跳到定义
> 5. 能添加评论
> 
> 这些功能基于这个组件都能实现，就是要在外层加逻辑（各种变着法的折腾`hunks`数组）。我们内部使用就有全部这些能力，另外还有在行号前面显示单元测试覆盖之类的……

好的，谢谢。我确实非常需要这些功能。

**Comment by otakustay** [comment]
https://codesandbox.io/s/react-diff-view-with-code-expansion-hzqzj

你可以参考一下这个sandbox，我加了高亮和代码展开的功能。我不建议把原本diff的3行相同代码也给隐藏了，用户会失去看diff的上下文的，只提供展开功能就行了

**Comment by Lcj-space** [comment]
> https://codesandbox.io/s/react-diff-view-with-code-expansion-hzqzj
> 
> 你可以参考一下这个sandbox，我加了高亮和代码展开的功能。我不建议把原本diff的3行相同代码也给隐藏了，用户会失去看diff的上下文的，只提供展开功能就行了

好的，非常感谢。

**Comment by Lcj-space** [comment]
> https://codesandbox.io/s/react-diff-view-with-code-expansion-hzqzj
> 
> 你可以参考一下这个sandbox，我加了高亮和代码展开的功能。我不建议把原本diff的3行相同代码也给隐藏了，用户会失去看diff的上下文的，只提供展开功能就行了

你好，我看了一下你的demo有个地方不是很明白，这块必须要有文件的原始格式吗。之前看你的文件类型只传一个diff 过的文件格式就可以了。
  const [hunksWithSourceExpansion, expandCode] = useSourceExpansion(file.hunks, SOURCE_CODE);

**Comment by otakustay** [comment]
如果你想展开相同的代码，就必须有左边那份的源文件。因为在diff文本里是没有那些相同行的代码的，没有这个源文件自然就不知道能显示啥了

源文件还有很多其它用处，比如在代码高亮的时候，你传一个`oldSource`过去，因为有了每一行的上下文，高亮就会变精准（比如多行注释在只有一部分的时候可能就不被当注释），这个我在demo里没写，你可以加上感受下

**Comment by Lcj-space** [comment]
> 如果你想展开相同的代码，就必须有左边那份的源文件。因为在diff文本里是没有那些相同行的代码的，没有这个源文件自然就不知道能显示啥了
> 
> 源文件还有很多其它用处，比如在代码高亮的时候，你传一个`oldSource`过去，因为有了每一行的上下文，高亮就会变精准（比如多行注释在只有一部分的时候可能就不被当注释），这个我在demo里没写，你可以加上感受下

嗯，对了大佬有一个地方就是评论数据怎么去渲染，那块目前看你写的两个例子没找到答案也很疑惑

**Comment by otakustay** [comment]
评论看这个：https://codesandbox.io/s/nifty-herschel-3w9s8
